#include "lib.h"
#include "i8259.h"
#include "keyboard.h"
#include "scancode.h"
#include "tests.h"
#define KEYBOARD_DATA_PORT 0x60
#define KEYBOARD_STATUS_PORT 0x64
#define KEYBOARD_COMMAND_PORT 0x64
#define KEYBOARD_IRQ_NUM 1

#define LSHIFT_IND  0
#define RSHIFT_IND  1
#define CAPSLOCK_IND 2
#define CTRL_IND 3
#define RELEASE(i) (i-128)
#define MAX_KEY_IND 127
#define TOTAL_KEY_NUM 128
int8_t pressed_key[TOTAL_KEY_NUM];
unsigned char keyboard_buffer[TOTAL_KEY_NUM+1];
unsigned char print_buffer[TOTAL_KEY_NUM+1];
int cap_status;
int cursor_ind;
int hold_num;
int terminal_read_ready;
/* keyboard initilization
 * 
 * initialize the keyboard and let it begin generating interrupts
 * Inputs: None
 * Outputs: None
 * Side Effects: irq 1 is enabled
 */
void keyboard_init()
{
    /* keyboard irq locate at 1*/
    init_scancodes_map();
    enable_irq(KEYBOARD_IRQ_NUM);
    memset(pressed_key, 0 , sizeof(pressed_key) );
    hold_num = 0;
    cursor_ind = 0;
    terminal_read_ready = 0;
    cap_status = 0;
}

unsigned char character_convert(unsigned char c)
{
    if( scancodes_map[c] ==0 ) return 0;
    unsigned char res = scancodes_map[c];
    if( (cap_status == 1) && (res>='a') && (res<='z') )
        res = special_convert_map[res];
    if( (pressed_key[SCANCODE_LEFTSHIFT]==1) || (pressed_key[SCANCODE_RIGHTSHIFT]==1) )
        res = special_convert_map[res];
    return res;
}

void scancode_processing(unsigned char c)
{
    int i;
    if( c>MAX_KEY_IND ) 
    {
        pressed_key[ RELEASE(c) ] = 0;
        hold_num--;
    }
    else
    {
        pressed_key[ c ] = 1;
        hold_num++;
        if( c== SCANCODE_CAPSLOCK ) cap_status = 1-cap_status;
        if( (c==SCANCODE_L) && (pressed_key[SCANCODE_LEFTCONTROL]==1)  )
        {
            clear();
            memset(keyboard_buffer, 0 , sizeof(keyboard_buffer) );
            cursor_ind = 0;
        }
        else if(scancodes_map[c]!=0)
        {
            if(cursor_ind==MAX_KEY_IND+1)
            {
                for(i=0; i<MAX_KEY_IND; i++)
                {
                    keyboard_buffer[i] = keyboard_buffer[i+1];
                }
                keyboard_buffer[MAX_KEY_IND] = character_convert(c);
            }
            else
            {
                keyboard_buffer[cursor_ind++] = character_convert(c);
            }
        }
    }
    
    if(c==SCANCODE_ENTER)
    {
        memcpy(print_buffer, keyboard_buffer, sizeof(keyboard_buffer) );
        memset(keyboard_buffer, 0 , sizeof(keyboard_buffer) );
        terminal_read_ready = 1;
        cursor_ind = 0;
    }
    
    if(c==SCANCODE_BACKSPACE)
    {
        keyboard_buffer[--cursor_ind] = '\0';
        //cursor_ind--;
    }
    /*
    if( c==SCANCODE_LEFTCONTROL ) special_condition[ CTRL_IND ] = 1;
    if( c==RELEASE(SCANCODE_LEFTCONTROL) ) special_condition[ CTRL_IND ] = 0;
    if( c==SCANCODE_LEFTSHIFT ) special_condition[ LSHIFT_IND ] = 1;
    if( c==RELEASE(SCANCODE_LEFTSHIFT) ) special_condition[ LSHIFT_IND ] = 0;
    if( c==SCANCODE_RIGHTSHIFT ) special_condition[ RSHIFT_IND ] = 1;
    if( c==RELEASE(SCANCODE_RIGHTSHIFT) )special_condition[ RSHIFT_IND ] = 0;
    if( c==CAPSLOCK_IND ) special_condition[ CAPSLOCK_IND ] = ( 1 - special_condition[ CAPSLOCK_IND ]);
    */
}
/* keyboard interrupt handler
 * 
 * handle the interrupt generated by keyboard
 * Inputs: None
 * Outputs: None
 * Side Effects: read ch from buffer, called the interruption test
 */
void keyboard_interrupt_handler()
{
    cli(); //disable interrupts
    //clear();
    unsigned char placeholder;
    while( (inb(KEYBOARD_STATUS_PORT)&0x1)>0 ) //use 0x1 to check the last bit, whether the buffer is still full.
    {
        placeholder = inb(KEYBOARD_DATA_PORT);
        scancode_processing(placeholder);
        interruption_test('k', placeholder);
        //printf("%c",keyboard_buffer);
    }
    puts_scroll_refresh(keyboard_buffer);
    send_eoi(KEYBOARD_IRQ_NUM);
    sti(); //re-enable interrupts
}

int32_t terminal_read(char* buf)
{
    if(terminal_read_ready==1)
    {
        memcpy(buf, print_buffer, sizeof(print_buffer));
        terminal_read_ready = 0;
        return 0;
    }
    else
    {
        return -1;
    }
}
