boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handler_wrapper.o: interrupt_handler_wrapper.S x86_desc.h \
  types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h lib.h interrupt_handler_wrapper.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h rtc.h idt.h interrupt_handler_wrapper.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h
lib.o: lib.c lib.h types.h
rtc.o: rtc.c i8259.h types.h lib.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
